### ISSUE TITLE
Migration to androidx

### ISSUE THREAD

**Issue by PampaZiya** [airbnb/epoxy#429]
How long will it take to migrate the Epoxy library to AndroidX? I realized when I did the "Refactor to Android X" (Out of curiosity) that the epoxy library broke (All recyclerview were android.support instead of androidx. inside epoxy)

**Comment by elihart** [comment]
It shouldn't be hard, but I have been on vacation and haven't worked on it yet. Can probably get to it this week unless somebody else wants to put up a PR

**Comment by jeffreydelooff** [comment]
I'd be happy to pick this up if you haven't started yet @elihart. Did a similar migration for another project.

**Comment by elihart** [comment]
@jeffreydelooff Sure, I would appreciate that, I haven't had the time yet.

Aren't the `androidx` packages not yet stable though? is it better to wait for final release? ie https://github.com/google/dagger/issues/1181

**Comment by jeffreydelooff** [comment]
True, you are right, they are all still in alpha. Can always start on the migration and only merge when everything is stable. Might already show issues with the new androidx libraries.

**Comment by elihart** [comment]
Sounds good to me, good idea

**Comment by PampaZiya** [comment]
Hello, thank you both for the update, I tried doing it myself by cloning and refactoring to androidx but failed to do so >,< There were a lot of errors that I didn't figure out how to fix nor had the time to. I agree on waiting for stable version, I did however try to refactor my working project to androidx and my only problem was with the epoxy library, not sure if that means an actual build would've worked though had this library been migrated.

**Comment by iffa** [comment]
Would love to see this. Starting to regret working with androidx/jetpack/etc. this early on lol. Any chance of an experimental release with androidx support?

**Comment by jeffreydelooff** [comment]
Still working on it. Almost migrated all of the submodules except for the samples. Unit tests are passing.

**Comment by vipulyaara** [comment]
Any idea when this will be available? I got everything working with Androidx except for Epoxy :(

**Comment by alexbchr** [comment]
The AndroidX libraries hit beta01 on July 2nd. I tried to migrate my project to AndroidX without any problems, except with the Epoxy Annotation processor, which complains that he can't find `android/support/annotation/LayoutRes`.

**Comment by elihart** [comment]
@jeffreydelooff is your branch stable? if so I can push a test version

**Comment by jeffreydelooff** [comment]
@elihart I'd have to update the versions and test again. All the tests were passing and tested it on my personal project. I think I ran in a few issues but most likely with other non-migrated libraries.

**Comment by elihart** [comment]
Once the PR is stable I'll push a snapshot

**Comment by PedroAlvarado** [comment]
AndroidX is at 1.0.0-rc01 as of August 6th. I'd be great to see a snapshot at that version since it is "considered feature-complete and its public API surface is stable".

**Comment by elihart** [comment]
https://github.com/airbnb/epoxy/pull/440 is now updated - I'll push a release for it today

**Comment by elihart** [comment]
I've pushed 3.0.0-rc1. I'll leave this as is for now until androidx is is fully released, and to make sure that nobody reports any issues with the build before I merge to master

Huge thanks to @jeffreydelooff for doing all this!

**Comment by jeffreydelooff** [comment]
No problem. We have been very happy with this library. :) Feel free to post any issues. I'd still like to test it on my personal project and see if there are any problems.

**Comment by vipulasri** [comment]
@elihart AndroidX hits 1.0.0 officially now. Hope epoxy with androidx will be available in the stable channel soon.

**Comment by elihart** [comment]
@vipulasri Does jetifier work correctly with Epoxy? Is there any reason Epoxy needs to upgrade asap instead of letting jetifier do the work for now?

**Comment by athornz** [comment]
I thought Jetifier didn't work on classes used within annotation processors?

**Comment by mradzinski** [comment]
@vipulasri @elihart as expected, Jetifier doesn't work with kapt nor apt for more than obvious reasons.

```
error: cannot find symbol
  @UiThread
   ^
  symbol:   class UiThread
  location: class ***
```
Eli, I'm actually testing 3.0.0-rc1 and generated models import `android.support.annotation.UiThread;` instead of `androidx.annotation.UiThread;` 😕.

**Comment by mradzinski** [comment]
@elihart My bad ✋. Had to dig a bit deeper, but although Gradle was pointing to an Epoxy generated model, the one to "blame" for the `UiThread` annotation is Butterknife, so nothing to do with Epoxy at all.

**Comment by elihart** [comment]
There were two big changes I wanted release before 3.0.0 - the new paged list support and the visibility event system. 

With the new 2.19.0 release these are out so I can work on releasing 3.0.0 with androidx.

The only thing that really needs to happen is a rebase of https://github.com/airbnb/epoxy/pull/440 to get it up to date with current master - then I will merge and push the final 3.0.0 release

I may not get to the rebase soon, so if someone else can help with it that'd be great

**Comment by jeffreydelooff** [comment]
I can see if I can update the deps to stable and rebasr to get things ready.

**Comment by simoks** [comment]
Hello, Can we use Epoxy library without migrating to AndroidX ?
Thanks!

**Comment by jeffreydelooff** [comment]
Yes. Use version 2.x.
