### ISSUE TITLE
@AutoModel no longer works with v4.1.0 and Kotlin

### ISSUE THREAD

**Issue by andreasmakeable** [airbnb/epoxy#1080]
The AutoModel feature no longer works with lateinit models in the 4.1.0 release.
Errors are thrown from all EpoxyController subclasses using @AutoModel

`ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1/Users/andreasdybdahl/Documents/Makeable/Android/mk-universet-app-2-0-android/app/build/generated/source/kapt/google_playDebug/dk/makeable/cookbook/ui/fragments/camps/MeasurementsStatusController_EpoxyHelper.java:23: error: <identifier> expected
    controller.loadingModel = new (@org.jetbrains.annotations.NotNull :: TitleLoaderBindingModel_)();
                                 ^/Users/andreasdybdahl/Documents/Makeable/Android/mk-universet-app-2-0-android/app/build/generated/source/kapt/google_playDebug/dk/makeable/cookbook/ui/fragments/camps/MeasurementsStatusController_EpoxyHelper.java:23: error: illegal start of expression`
